---
gogs_user: gogs
gogs_download_url: https://github.com/gogs/gogs/releases/download/v0.11.91/linux_amd64.tar.gz
gogs_install_binary: no
gogs_server_name:
  - git.debauer.net

certbot_create_if_missing: false
certbot_create_method: standalone
certbot_admin_email: admin@debauer.net