# from GitHub, overriding the name and specifying a specific tag
roles:
  - name: ansible-tasmota
    src: https://github.com/tobias-richter/ansible-tasmota
    version: master

  - src: https://github.com/debauer/ansible-grafana
    name: ansible-grafana

  - src: https://github.com/Oefenweb/ansible-duply
    name: ansible-duply

  - src: https://github.com/Oefenweb/ansible-duplicity
    name: ansible-duplicity

  - src: https://github.com/borgbase/ansible-role-borgbackup
    name: ansible-borg

  - src: https://github.com/bithium/ansible-role-lighttpd
    name: ansible-lighttpd

