---
- hosts: herbert
  become: yes
  vars_files:
    - ./vars/secrets.yml

  roles:
    - role: users
      vars:
        users:
          - { name: keya }
          - { name: debauer }
        key_files:
          - public_keys/bauer-bauer
          - public_keys/bauer-zerbrechlich
    - role: packages
    - role: influxdb
      vars:
        influx_admin_password: "{{ vault_influx_admin_password }}"
    - role: ansible-grafana
      vars:
        grafana_admin_password: "{{ vault_grafana_admin_password }}"
    - role: grafana
      vars:
        grafana_admin_password: "{{ vault_grafana_admin_password }}"


