---
- hosts: herbert
  become: yes
  vars_files:
    - ./vars/secrets.yml
  vars:
    influx_admin_password: "{{ vault_influx_admin_password }}"
    grafana_admin_password: "{{ vault_grafana_admin_password }}"

  roles:
    - role: projects
    - role: hass
    - role: users
      vars:
        users:
          - { name: keya }
          - { name: debauer }
        key_files:
          - public_keys/bauer-bauer
          - public_keys/bauer-zerbrechlich
    - role: packages
      vars:
        apt_additional:
          - mosquitto
          - mosquitto-clients
        update_apt: false
    - role: influxdb
    - role: grafana
