---
- name: install influxdb
  block:
    - name: Import InfluxDB GPG signing key
      apt_key: url=https://repos.influxdata.com/influxdb.key state=present

    - name: Add InfluxDB repository
      apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

    - name: Install InfluxDB packages
      apt: name=influxdb state=present

    - name: Modify InfluxDB hostname
      replace:
        dest=/etc/influxdb/influxdb.conf
        regexp='hostname = "localhost"'
        replace='hostname = "{{ ansible_hostname }}"'
        backup=yes

    - name: Start the InfluxDB service
      service: name=influxdb state=restarted
  when: install_influx

- name: add admin user
  uri:
    url: "http://{{ inventory_hostname }}:8086/query"
    method: POST
    body: "q=CREATE USER admin WITH PASSWORD '{{ influx_admin_password }}' WITH ALL PRIVILEGES"

- name: create datebases
  uri:
    url: "http://{{ inventory_hostname }}:8086/query"
    method: POST
    body: "q=CREATE DATABASE {{ item }}"
  with_items: "{{ influx_databases }}"
