---
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualenv
    - python3
    - python3-pip
    - python3-dev

- name: create user
  user:
    name: hass
    home: /home/hass
    shell: /bin/false
    system: yes
    state: present

- name: install hass
  become: yes
  become_user: hass
  pip:
    name: homeassistant
    virtualenv: /home/hass/venv
    virtualenv_python: python3

- name: copy systemd service file
  template:
    src: hass.service
    dest: /etc/systemd/system/hass.service

- name: enable service and start it
  systemd:
    name: hass
    state: started
    enabled: yes
    daemon_reload: yes