---
- name: Set the GPU memory split value via raspi-config - 128 iS the minimum for the camera
  command: raspi-config nonint do_memory_split gpu_mem_1024=256

- name: Enable the camera via raspi-config
  command: raspi-config nonint do_camera 0

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: http://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
    state: present

- apt_repository:
    repo: deb http://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main
    state: present

- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: no
    autoremove: yes

- name: Install uv4l packages
  package:
    name: "{{ uv4l_packages }}"
    state: present

- name: Start service raspicam
  service:
    name: uv4l_raspicam
    state: started

- name: set daemon in  /etc/uv4l/uv4l-raspicam.conf
  lineinfile:
    dest:  /etc/uv4l/uv4l-raspicam.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?# width', line: 'width = 640' }
    - { regexp: '^#?# height', line: 'height = 480' }

- name: Start service raspicam
  service:
    name: uv4l_raspicam
    state: restarted

#- name: reboot 
#  reboot:
