---
- name: Install motion packages
  package:
    name: "{{ motion_packages }}"
    state: present

- name: set daemon in /etc/default/motion
  lineinfile:
    dest: /etc/default/motion
    regexp: "^#?start_motion_daemon=no"
    line: "start_motion_daemon=yes"
    state: present

- name: set daemon in /etc/motion/motion.conf
  lineinfile:
    dest: /etc/motion/motion.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^#?daemon', line: 'daemon on' }
    - { regexp: '^#?width', line: 'width 480' }
    - { regexp: '^#?height', line: 'height 360' }
    - { regexp: '^#?stream_port', line: 'stream_port 8081' }
    - { regexp: '^#?stream_localhost', line: 'stream_localhost off' }
    - { regexp: '^#?framerate', line: 'framerate 10' }


- name: restart daemon
  command: systemctl restart motion
