---
- name: install general pip dependencies
  become: yes
  become_user: '{{ item }}'
  pip:
    name: "{{ packages.for_users }}"
    state: present
    executable: /usr/bin/pip3
  with_items: "{{ users }}"

- name: install general pip dependencies for default python3
  become: yes
  become_user: 'root'
  pip:
    name: "{{ packages.for_root }}"
    state: present
    executable: /usr/bin/pip3
  with_items: "{{ users }}"